### ISSUE TITLE
Relation of MOO.jl to Milt Output Optimize

### ISSUE THREAD

**Issue by KZiemian** [odow/MOO.jl#1]
I was making timestamps to [_Cows, Lakes, and a JuMP extension..._](https://www.youtube.com/watch?v=LDgNmsOCl1A) talk from JuliaCon 2017 and I was searching for link for MOO and Moa.jl. Now I quite confused, which is which. Can someone explain to me how this currently works?

**Comment by odow** [comment]
MOO.jl is unrelated.

For the cow stuff:

### Maintained (you can use and will work):

There is one generic library for SDDP:

 * https://github.com/odow/SDDP.jl

### Unmaintained (won't work, and won't be able to install. For interest only):

There are three "application" examples:

 * https://github.com/odow/MOO
 * https://github.com/odow/MilkPOWDER
 * https://github.com/odow/MilkPOWDERII

and a dynamic programming library:

 * https://github.com/odow/DynamicProgramming.jl

**Comment by KZiemian** [comment]
Thank you for explanation. I guess a lot of names changed in the 5 years that pass. Can I ask about what happened to Moa.jl? Should I point people to SDDP.jl? Current state of timestamps is below, but I need to make hyperlinks to work correctly. Of course, timestamps maybe not good and need a improvements.

00:00 Welcome!
00:10 What cows have to do with Julia?
00:36 Julia meats Daisy in the filed of multi-stage stochastic optimization
00:51 New Zealand dairy farm on which I grew up
01:48 Hydro-thermal scheduling problem
03:10 [MOO](https://github.com/odow/MOO): The Milk Output Optimizer
04:22 Stochastic Dual Dynamic Programming (SDDP)
04:51 Problem with solving SDDP problems with standard languages
05:18 Why not do it in Julia? Lot of people had this idea
05:35 Moa.jl: Multi-stage Optimisation Application
06:29 Moa.jl is quite good
07:14 Takeaway thoughts
07:38 Obligatory pictures of cows

**Comment by odow** [comment]
Moa.jl became SDDP.jl. 

If you're interested in this, send me an email (https://odow.github.io) and we can discuss further. This doesn't need to be on GutHub.
